name: Build All Kernels

on:
  workflow_dispatch:
    inputs:
      KERNEL_SUFFIX:
        description: '内核名称修改(可改中文和emoji)'
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444-4k'
      KERNEL_TIME:
        description: "内核构建日期更改(默认为原厂)"
        required: true
        default: 'Tue Dec 17 23:36:49 UTC 2024'
      enable_feature_x:
        description: "是否启用kpm"
        required: false
        default: true
        type: boolean
      enable_feature_y:
        description: "是否启用lz4kd"
        required: false
        default: true
        type: boolean
      enable_feature_z:
        description: "是否添加风驰驱动"
        required: false
        default: true
        type: boolean

jobs:
  trigger_builds:
    name: Trigger Device Builds
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.meta.outputs.run-id }}
    steps:
      - name: Generate unique run ID
        id: meta
        run: echo "run-id=$(date +%s)" >> $GITHUB_OUTPUT
        
      - name: Trigger oneplus_13
        uses: convictional/trigger-workflow-and-wait@v1.8.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: oneplus_13.yml
          ref: ${{ github.ref }}
          wait_interval: 30
          inputs: '{"KERNEL_SUFFIX": "${{ inputs.KERNEL_SUFFIX }}", "KERNEL_TIME": "${{ inputs.KERNEL_TIME }}", "enable_feature_x": ${{ inputs.enable_feature_x }}, "enable_feature_y": ${{ inputs.enable_feature_y }}, "enable_feature_z": ${{ inputs.enable_feature_z }}, "parent_run_id": "${{ steps.meta.outputs.run-id }}"}'
          
      - name: Trigger oneplus_13T
        uses: convictional/trigger-workflow-and-wait@v1.8.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: oneplus_13T.yml
          ref: ${{ github.ref }}
          wait_interval: 30
          inputs: '{"KERNEL_SUFFIX": "${{ inputs.KERNEL_SUFFIX }}", "KERNEL_TIME": "${{ inputs.KERNEL_TIME }}", "enable_feature_x": ${{ inputs.enable_feature_x }}, "enable_feature_y": ${{ inputs.enable_feature_y }}, "enable_feature_z": ${{ inputs.enable_feature_z }}, "parent_run_id": "${{ steps.meta.outputs.run-id }}"}'
          
      - name: Trigger oneplus_ace5_pro
        uses: convictional/trigger-workflow-and-wait@v1.8.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: oneplus_ace5_pro.yml
          ref: ${{ github.ref }}
          wait_interval: 30
          inputs: '{"KERNEL_SUFFIX": "${{ inputs.KERNEL_SUFFIX }}", "KERNEL_TIME": "${{ inputs.KERNEL_TIME }}", "enable_feature_x": ${{ inputs.enable_feature_x }}, "enable_feature_y": ${{ inputs.enable_feature_y }}, "enable_feature_z": ${{ inputs.enable_feature_z }}, "parent_run_id": "${{ steps.meta.outputs.run-id }}"}'
          
      - name: Trigger oneplus_pad_2_pro
        uses: convictional/trigger-workflow-and-wait@v1.8.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: oneplus_pad_2_pro.yml
          ref: ${{ github.ref }}
          wait_interval: 30
          inputs: '{"KERNEL_SUFFIX": "${{ inputs.KERNEL_SUFFIX }}", "KERNEL_TIME": "${{ inputs.KERNEL_TIME }}", "enable_feature_x": ${{ inputs.enable_feature_x }}, "enable_feature_y": ${{ inputs.enable_feature_y }}, "enable_feature_z": ${{ inputs.enable_feature_z }}, "parent_run_id": "${{ steps.meta.outputs.run-id }}"}'

  collect_artifacts:
    name: Collect All Artifacts
    needs: trigger_builds
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: combined_artifacts
          
      - name: Create Download Package
        run: |
          cd combined_artifacts
          zip -r ../all_kernels.zip .
          cd ..
        shell: bash
        
      - name: Upload Combined Package
        uses: actions/upload-artifact@v4
        with:
          name: ALL_KERNELS_PACKAGE
          path: all_kernels.zip
